export { default as Header } from './Header'
export { default as Heading } from './Heading'
export { default as Intro } from './Intro'
export { default as Divider } from './Divider'
export { default as About } from './About'
export { default as Projects } from './Projects'
