export { default as Header } from './Header'
export { default as BackgroundDecorations } from './BackgroundDecorations'
export { default as NavbarBackground } from './NavbarBackground '
export { default as Heading } from './Heading'
export { default as Intro } from './Intro'
export { default as Divider } from './Divider'
export { default as About } from './About'
export { default as Projects } from './Projects'
export { default as Skills } from './Skills'
export { default as Courses } from './Courses'
export { default as ContactMe } from './ContactMe'
export { default as WhatsApp } from './WhatsApp'
export { default as ThemeSwitch } from './ThemeSwitch'
export { default as Footer } from './Footer'
